import {STATSBOMB_LOGO} from '@/lib/touchline/branding';
import {aggregate,fmt,metrics,percentile,type Row,type Entity,type Metric,type Shot} from '@/lib/touchline/data';
export type ChartKind='scatter'|'bar'|'trend'|'radar'|'shots';
export type ChartConfig={kind:ChartKind;metric:Metric;xMetric:Metric;title:string;color:string;labels:boolean;per90:boolean;by:'player'|'team';note:string;};
export function Chart({entities,rows,shots,config,source,subtitle,selected=[],statsbomb=false,dark=false}:{entities:Entity[];rows:Row[];shots:Shot[];config:ChartConfig;source:string;subtitle:string;selected?:string[];statsbomb?:boolean;dark?:boolean}){
 const {kind,metric,xMetric,labels,per90,by,title,note}=config;const color=dark?({'#490627':'#f2aacb','#935146':'#edb496','#bd6063':'#f7acb1','#7b2800':'#ffc18d','#8e3b39':'#ffb1ab','#0067a5':'#78c8ff','#007b71':'#65dbc9'}[config.color]||config.color):config.color;const W=900,H=540,left=80,right=835,top=105,bottom=430;
 const pool=selected.length?entities.filter(e=>selected.includes(e.name)):entities;
 const data=pool.filter(e=>e.values[metric]!==null).slice().sort((a,b)=>(b.values[metric]||0)-(a.values[metric]||0));
 const max=(m:Metric)=>Math.max(...data.map(e=>e.values[m]||0),1)*1.12;
 const y=(n:number)=>bottom-n/max(metric)*(bottom-top),x=(n:number)=>left+n/max(xMetric)*(right-left);
 const label=(m:Metric)=>metrics[m].label+(per90&&m!=='pass_pct'?' / 90':'');
 const empty=!data.length;const ticks=Array.from({length:5},(_,i)=>i/4);
 const times=[...new Set(rows.map(r=>r.date))].sort().map(date=>{const rs=rows.filter(r=>r.date===date&&(!selected.length||selected.includes(by==='player'?r.player:r.team)));return {date,value:aggregate(rs,'team',false).reduce((a,e)=>a+(e.values[metric]||0),0),rs};}).map(t=>{let n:number|null=null;const all=aggregate(t.rs.map(r=>({...r,team:'All'})),'team',per90);if(all.length)n=all[0].values[metric];return {...t,value:n};});
 const trendMax=Math.max(1,...times.map(t=>t.value||0))*1.1;
 return <svg xmlns="http://www.w3.org/2000/svg" viewBox={`0 0 ${W} ${H}`} role="img" aria-label={title||`${metrics[metric].label} chart`} className="analytics-svg">
 <metadata>{JSON.stringify({source,filters:subtitle,selected,configuration:config})}</metadata><rect width={W} height={H} fill={dark?'#211b20':'#ffffff'}/><g fontFamily="Arial, Helvetica, sans-serif" fill={dark?'#f5edef':'#291b23'}><text x="34" y="37" fontSize="23" fontWeight="700">{(title||`${metrics[metric].label} analysis`).slice(0,65)}</text><text x="34" y="62" fontSize="13" fill={dark?'#ded1d9':'#534650'}>{subtitle.slice(0,110)}</text>
 {empty?<text x="450" y="265" textAnchor="middle" fontSize="18">No available values for this selection</text>:<>
 {kind==='scatter'&&<>{ticks.map(t=><g key={t}><line x1={left} x2={right} y1={bottom-t*(bottom-top)} y2={bottom-t*(bottom-top)} stroke={dark?'#4b3943':'#e9dfe3'}/><text x={left-12} y={bottom-t*(bottom-top)+5} textAnchor="end" fontSize="13">{fmt(t*max(metric))}</text><text x={left+t*(right-left)} y={bottom+22} textAnchor="middle" fontSize="13">{fmt(t*max(xMetric))}</text></g>)}<text x="455" y="476" textAnchor="middle" fontSize="14">{label(xMetric)}</text><text transform="translate(22 280) rotate(-90)" textAnchor="middle" fontSize="14">{label(metric)}</text>{data.filter(e=>e.values[xMetric]!==null).map((e,i)=><g key={e.name+e.team}><circle cx={x(e.values[xMetric]||0)} cy={y(e.values[metric]||0)} r={selected.includes(e.name)?9:6.5} fill={color} fillOpacity={.95} stroke="white" strokeWidth="2"><title>{`${e.name}: ${label(xMetric)} ${fmt(e.values[xMetric])}; ${label(metric)} ${fmt(e.values[metric])}`}</title></circle>{labels&&i<3&&<text x={x(e.values[xMetric]||0)+(x(e.values[xMetric]||0)>700?-10:10)} textAnchor={x(e.values[xMetric]||0)>700?'end':'start'} y={y(e.values[metric]||0)-9} fontSize="12">{e.name}</text>}</g>)}</>}
 {kind==='bar'&&<>{data.slice(0,10).map((e,i)=>{const yy=top+i*31;return <g key={e.name+e.team}><text x="173" y={yy+17} textAnchor="end" fontSize="13">{e.name.slice(0,22)}</text><rect x="187" y={yy} height="23" width={(e.values[metric]||0)/max(metric)*575} fill={color} rx="3"/><text x={196+(e.values[metric]||0)/max(metric)*575} y={yy+17} fontSize="13">{fmt(e.values[metric])}</text></g>})}<text x="450" y="470" textAnchor="middle" fontSize="14">{label(metric)} · Top {Math.min(10,data.length)} in the current selection</text></>}
 {kind==='trend'&&<>{ticks.map(t=><g key={t}><line x1={left} x2={right} y1={bottom-t*(bottom-top)} y2={bottom-t*(bottom-top)} stroke={dark?'#4b3943':'#e9dfe3'}/><text x="65" y={bottom-t*(bottom-top)+5} textAnchor="end" fontSize="13">{fmt(t*trendMax)}</text></g>)}{times.map((t,i)=>{const xx=left+i*(right-left)/Math.max(1,times.length-1),yy=bottom-(t.value||0)/trendMax*(bottom-top),prev=times[i-1];return <g key={t.date}>{i>0&&t.value!==null&&prev.value!==null&&<line x1={left+(i-1)*(right-left)/Math.max(1,times.length-1)} x2={xx} y1={bottom-prev.value/trendMax*(bottom-top)} y2={yy} stroke={color} strokeWidth="3"/>}{t.value!==null&&<circle cx={xx} cy={yy} r="5" fill={color}><title>{`${t.date}: ${fmt(t.value)}`}</title></circle>}{i%Math.max(1,Math.ceil(times.length/8))===0&&<text x={xx} y="455" textAnchor="middle" fontSize="12">{t.date.slice(5)}</text>}</g>})}<text x="450" y="480" fontSize="14" textAnchor="middle">{label(metric)} · Aggregated by match date</text></>}
 {kind==='radar'&&(()=>{const ms:Metric[]=['goals','assists','shots','xg','passes','tackles'];const point=(i:number,r:number)=>[440+Math.cos(i*Math.PI/3-Math.PI/2)*r,280+Math.sin(i*Math.PI/3-Math.PI/2)*r];return <>{[.25,.5,.75,1].map(f=><polygon key={f} points={ms.map((_,i)=>point(i,145*f).join(',')).join(' ')} fill="none" stroke={dark?'#4b3943':'#e9dfe3'}/>)}{ms.map((m,i)=>{const [xx,yy]=point(i,178);return <text key={m} x={xx} y={yy} textAnchor="middle" fontSize="13">{metrics[m].label}</text>})}{data.filter(e=>ms.every(m=>percentile(entities,e,m)!==null)).slice(0,3).map((e,j)=>{const colors=dark?['#f2aacb','#78c8ff','#65dbc9']:['#490627','#0067a5','#007b71'];return <g key={e.name}><polygon points={ms.map((m,i)=>point(i,(percentile(entities,e,m)||0)*1.45).join(',')).join(' ')} fill={colors[j]} fillOpacity=".08" stroke={colors[j]} strokeWidth="3" strokeDasharray={[undefined,'8 4','2 4'][j]}/><text x={70+j*270} y="482" fontSize="13" fill={colors[j]}>{`${['Solid','Dashed','Dotted'][j]}: ${e.name.slice(0,25)}`}</text></g>})}<text x="610" y="105" fontSize="12">Percentile within visible cohort</text>{!data.some(e=>ms.every(m=>percentile(entities,e,m)!==null))&&<text x="440" y="280" textAnchor="middle" fontSize="14">Insufficient complete profiles</text>}</>})()}
 {kind==='shots'&&<><rect x="110" y="110" width="680" height="330" rx="1" fill={dark?'#35252e':'#f8ecee'} stroke={dark?'#ad8497':'#ad8497'}/><line x1="450" x2="450" y1="110" y2="440" stroke={dark?'#ad8497':'#ad8497'}/><circle cx="450" cy="275" r="45" fill="none" stroke={dark?'#ad8497':'#ad8497'}/><rect x="110" y="179" width="93" height="192" fill="none" stroke={dark?'#ad8497':'#ad8497'}/><rect x="697" y="179" width="93" height="192" fill="none" stroke={dark?'#ad8497':'#ad8497'}/><rect x="755" y="231" width="35" height="88" fill="none" stroke={dark?'#ad8497':'#ad8497'}/>{shots.filter(s=>rows.some(r=>r.id===s.rowId&&(!selected.length||selected.includes(by==='player'?r.player:r.team)))).map((s,i)=>{const cx=110+s.x/120*680,cy=110+s.y/80*330,r=4+s.xg*17;return <g key={i}><title>{`${s.goal?'Goal':'Shot'} · xG ${s.xg}`}</title>{s.goal?<polygon points={`${cx},${cy-r} ${cx+r},${cy} ${cx},${cy+r} ${cx-r},${cy}`} fill={color} stroke={dark?'#fff':'#201b20'} strokeWidth="1.5"/>:<circle cx={cx} cy={cy} r={r} fill={dark?'#211b20':'#fff'} stroke={color} strokeWidth="2"/>}</g>;})}<text x="110" y="473" fontSize="13">Diamond = goal · Circle = other shot · Size = xG · Attacking to the right</text></>}
 </>}
 <line x1="34" x2="866" y1="498" y2="498" stroke={dark?'#4b3943':'#e9dfe3'}/><text x="34" y="519" fontSize="11" fill={dark?'#ded1d9':'#534650'}>{source.slice(0,100)}</text><g>{statsbomb?<><rect x="678" y="502" width="190" height="32" fill="white" rx="2"/><image data-attribution="statsbomb" href={STATSBOMB_LOGO} x="686" y="506" width="174" height="24" preserveAspectRatio="xMidYMid meet"><title>StatsBomb — data source</title></image></>:<text x="866" y="519" fontSize="11" textAnchor="end" fill={dark?'#ded1d9':'#534650'}>TOUCHLINE STUDIO</text>}</g>{note&&<title>{`Analyst note: ${note}`}</title>}</g></svg>;
}
