export type Metric = 'goals'|'assists'|'shots'|'xg'|'passes'|'tackles'|'pass_pct'|'sot'|'npxg'|'key_passes'|'dribbles'|'carries'|'interceptions'|'recoveries'|'pressures';
export type Row = {id:string; player:string;team:string;position:string;competition:string;season:string;date:string;minutes:number;goals:number|null;assists:number|null;shots:number|null;xg:number|null;passes:number|null;completed:number|null;tackles:number|null;sot?:number|null;npxg?:number|null;key_passes?:number|null;dribbles?:number|null;carries?:number|null;interceptions?:number|null;recoveries?:number|null;pressures?:number|null};
export type Shot={rowId:string;x:number;y:number;xg:number;goal:boolean};
export const metrics: Record<Metric,{label:string;definition:string}>={sot:{label:'Shots on target',definition:'Shots with Goal, Saved, or Saved to Post outcomes. Blocked shots and Saved Off Target are excluded. Penalty shoot-outs are excluded.'},npxg:{label:'Non-penalty xG',definition:'Sum of StatsBomb shot xG excluding shots of type Penalty. Model probabilities are not a guarantee of scoring.'},key_passes:{label:'Key passes',definition:'Pass events marked shot_assist by StatsBomb, including passes that lead to goals. This is a shot-assist count, not expected assists.'},dribbles:{label:'Successful dribbles',definition:'Dribble events with outcome Complete. Carries without an attempted take-on are counted separately.'},carries:{label:'Carries',definition:'Number of recorded Carry events. This counts actions, not distance or progressive carries.'},interceptions:{label:'Interceptions',definition:'Recorded Interception events, across outcomes. This is an attempt count, not only retained-possession interceptions.'},recoveries:{label:'Ball recoveries',definition:'Ball Recovery events excluding those marked recovery_failure. This is distinct from tackles and interceptions.'},pressures:{label:'Pressures',definition:'Recorded Pressure events. Counts depend on the provider’s event collection and are not a direct measure of defensive quality.'},goals:{label:'Goals',definition:'Recorded goals, excluding own goals.'},assists:{label:'Assists',definition:'Pass events marked goal_assist by StatsBomb. Other providers may use different assist definitions.'},shots:{label:'Shots',definition:'Total recorded attempts, including blocked shots.'},xg:{label:'Expected goals',definition:'Sum of available shot probabilities. Do not mix different providers’ xG models.'},passes:{label:'Pass attempts',definition:'Total recorded pass attempts.'},tackles:{label:'Tackles',definition:'Duel events of type Tackle, across outcomes. This is tackle attempts rather than tackles won.'},pass_pct:{label:'Pass completion %',definition:'100 × completed passes / attempted passes, aggregated from counts. Never averaged across matches.'}};
export type Entity={name:string;team:string;position:string;minutes:number;matches:number;values:Record<Metric,number|null>};
export function aggregate(rows:Row[],by:'player'|'team',per90:boolean):Entity[]{
 const groups=new Map<string,Row[]>();rows.forEach(r=>{const k=by==='player'?`${r.team}\0${r.player}`:r.team;groups.set(k,[...(groups.get(k)||[]),r]);});
 return [...groups.values()].map(rs=>{const minutes=rs.reduce((a,r)=>a+r.minutes,0);const val=(key:keyof Row)=>rs.every(r=>r[key]!==null&&r[key]!==undefined)?rs.reduce((a,r)=>a+Number(r[key]),0):null;
 const values={} as Entity['values'];for(const metric of Object.keys(metrics) as Metric[]){if(metric==='pass_pct'){const a=val('passes'),b=val('completed');values[metric]=a&&b!==null?b/a*100:null;}else {const n=val(metric);values[metric]=n===null?null:per90?(minutes>0?n/minutes*90:null):n;}}
 return {name:by==='player'?rs[0].player:rs[0].team,team:rs[0].team,position:by==='player'?rs[0].position:'TEAM',minutes,matches:new Set(rs.map(r=>r.date)).size,values};});
}
export function fmt(n:number|null){return n===null?'—':new Intl.NumberFormat('en',{maximumFractionDigits:2}).format(n);}
export function percentile(entities:Entity[],entity:Entity,metric:Metric){const vals=entities.map(e=>e.values[metric]).filter((v):v is number=>v!==null),n=entity.values[metric];if(n===null||vals.length<2)return null;return 100*(vals.filter(v=>v<n).length+(vals.filter(v=>v===n).length-1)/2)/Math.max(1,vals.length-1);}
